[package]
name = "logster"
version = "0.1.0"
edition = "2021"
authors = ["Rishub <itsrihsub@gmail.com>"]
description = "A fast CLI tool written in Rust"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"
ahash = "0.8"
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0

[[bin]]
name = "logster"
path = "src/main.rs"
